### Forward Propagation

In [14]:
import numpy as np


def feed_forward(inputs, outputs, weights):
    pre_hidden = np.dot(inputs, weights[0]) + weights[1]
    # print(pre_hidden)
    hidden = 1 / (1 + np.exp(-pre_hidden))
    # print(hidden)
    pred_out = np.dot(hidden, weights[2]) + weights[3]
    # print(pred_out)
    mean_squared_error = np.mean(np.square(pred_out - outputs))
    return mean_squared_error

In [21]:
x = np.array([[1, 1]])
y = np.array([[0]])
w = [np.array([[.8, .4, .3], [.2, .9, .5]]), np.array([0, 0, 0]),
     np.array([[.3], [.5], [.9]]), np.array([0])]

feed_forward(x, y, w)

1.5208120789621902

In [22]:
from copy import deepcopy


def update_weights(inputs, outputs, weights, lr):
    original_weights = deepcopy(weights)
    temp_weights = deepcopy(weights)
    updated_weights = deepcopy(weights)
    original_loss = feed_forward(inputs, outputs, original_weights)
    for i, layer in enumerate(original_weights):
        for index, weight in np.ndenumerate(layer):
            temp_weights = deepcopy(weights)
            temp_weights[i][index] += 0.0001
            _loss_plus = feed_forward(inputs, outputs, temp_weights)
            grad = (_loss_plus - original_loss) / (0.0001)
            updated_weights[i][index] -= grad * lr
    return updated_weights, original_loss

In [32]:
w, loss = update_weights(x, y, w, .1)
w, loss

([array([[0.78773887, 0.36619277, 0.1859992 ],
         [0.18773887, 0.86619277, 0.3859992 ]]),
  array([0, 0, 0]),
  array([[-0.23800185],
         [-0.07693925],
         [ 0.40589043]]),
  array([0])],
 0.0015449286983357591)